name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Action
        uses: mateo546/Simple-Actions@main
      - name: mateo colombo
        run: echo hola mundo
