name: Actions Workflow

on:
  schedule:
    -cron: "* * * * *" 
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token}}"
      - name: Simple JS Action
        id: greet
        uses: Github-Actions-Org-Mateo/Github-Actions-2@v1
        with:
          who-to-greet: Mateo
      - name: Log Greeting Time
        run: echo "{{ steps.greet.outputs.time }}"    